version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"

volumes:
  postgres_data:
