version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: none

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    logging:
      driver: none

  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    logging:
      driver: none

  app:
    build: .
    ports:
      - '3333:3333'
    command: yarn start
    depends_on:
      - postgres
    volumes:
      - .:/usr/app

volumes:
  postgres_data:
